# HTTP 服务器
http_server:
  # 端口
  port: 8000
  # 调试模式
  debug: true
# 数据库
database:
  # 数据库的服务器地址
  datasource: localhost
  #
  database: CW_BigDb
  # 数据库的登录帐号
  loginName: test
  # 数据库的密码
  password: test
